### ISSUE TITLE
Eric Kiel - personal work

### ISSUE THREAD

**Issue by anny234** [TechnionYP5779/team3#110]

**Comment by eric-K1** [comment]
## Sprint Zero
* The TDD I worked was creating a fluent api for an arithmetic sequence over BigIntegers (issue #62).
* Integrating SonarQube was a bit difficult and unintuitive (#86).
* Worked on various refactoring issues: #103, #67, #48, #47, #49.
* Created unit tests for forget, empty, unbox and Truth: #32, #23, #22, #21.

**Comment by yossigil** [comment]
You were expected to report much more than that.

**Comment by yossigil** [comment]
MINIMAL REPORT, WHICH APPEARS TO PRESENT LITTLE WORK. 
TOO BAD

**Comment by eric-K1** [comment]
## Sprint One
* Helped implement Auth0 integration, finishing Rani's work. Issue #240. Read the relevant documentation on Auth0's site, replaced the temporary login page in the site with a redirection to Auth0 that then redirects you back to the user's home page. Modified the backend to use the new UIDs that Auth0 provides, instead of our temporary, local id's. I also added integrated a filter that blocks pages that should only be available to users, and made them require a log in. Afterwards I added Google/Facebook authentication using Auth0.
* Created a class that interfaces with the database and returns wrapper objects that represent entries in the database. By using such a design, we could replace what database we use in future by changing only the implementation and leaving the function declerations the as they are. Issue #150. 
* Chose what DB to use for Sprint One, researching various different options. Issue #132.
* I also created one of the wrapper classes I mentioned: #149. I worked on several issues that required maintaining the DBManager class: #206, #205, #201, #187.
