### ISSUE TITLE
For each class X, test class should be named XTest, not X_Test, neither XTests, nor xTests, etc. this includes case matching, and also folder matching

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#114]

**Comment by IluhaBratan** [comment]
Finished, note: the rule I went with was as following:
For either class Upper or upper the test class would be UpperTest.

**Comment by yossigil** [comment]
don't invent your own rules.

**Comment by IliaSmagloy** [comment]
Hi, what I meant was the instructions were unclear as to what should I do for class names longer than 1 char (in the sense of should all of the class name should be uppercase or only the first letter). Because of that, I've decided to add my convention to it. I will of course change it if you prefer it done otherwise - I just didn't understand it from the original issue.

I will close the issue or change as asked after I see your answer, thank you :)

**Comment by yossigil** [comment]
i am not sure I understand the question. 
To repeast if class name is X, then the test is XTest.

DO NOT USE YOUR OWN CONVENTION
